services:
  openstreetmap-quality-framework-db:
    image: postgis/postgis:17-3.5
    container_name: openstreetmap-quality-framework-db
    command: ["postgres", "-c", "max_connections=300"]
    environment:
      POSTGRES_DB: osm_quality_framework
      POSTGRES_USER: osm_quality_framework_user
      POSTGRES_PASSWORD: osm_quality_framework_pass
    ports:
      - "54322:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  openstreetmap-quality-framework:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        OSM2PGSQL_REPO_URL: https://github.com/osm2pgsql-dev/osm2pgsql.git
        OSM2PGSQL_REPO_BRANCH: master
        OSMOSIS_REPO_TAR: https://github.com/openstreetmap/osmosis/releases/download/0.49.2/osmosis-0.49.2.tar
    container_name: openstreetmap-quality-framework
    ports:
      - "8080:8080"
    depends_on:
      - openstreetmap-quality-framework-db
    environment:
      OSM_QUALITY_FRAMEWORK_DATABASE: osm_quality_framework
      OSM_QUALITY_FRAMEWORK_DATABASE_HOST: openstreetmap-quality-framework-db
      OSM_QUALITY_FRAMEWORK_DATABASE_PORT: 5432
      OSM_QUALITY_FRAMEWORK_DATABASE_USERNAME: osm_quality_framework_user
      OSM_QUALITY_FRAMEWORK_DATABASE_PASSWORD: osm_quality_framework_pass
    volumes:
      - ./docker/data/pbf/data.osm.pbf:/app/import/data.osm.pbf:ro

volumes:
  db-data:

networks:
  default:
    name: openstreetmap-quality-framework